daemon off;
events {}
http {
 server {
  # listen 443 ssl;
  # ssl_certificate /run/secrets/server.crt;
  # ssl_certificate_key /run/secrets/server.key;
  # ssl_protocols TLSv1.2 TLSv1.3;

  listen 80; # for the test

  server_name "$DOMAIN_NAME";

  root /var/www/wordpress;
  index index.php index.html;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass wordpress_php_fpm:9000;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;
  }
 }
}
