events {}

http {
  server {
    # listen 443 is required
    listen 80;
    listen 443;
    
    # mounted named volume of wordpress_website_files
    # firstly, without php, test with index.html
    location / {
      root  /usr/share/nginx/html;
      index index.php index.html;
    }
  }
}

