daemon off;
events {}
http {
 server {
  listen 443 ssl;
  ssl_certificate /run/secrets/server.crt;
  ssl_certificate_key /run/secrets/server.key;
  ssl_protocols TLSv1.2 TLSv1.3;

  server_name ymizuniw.42.fr;

  root /var/www/wordpress;
  index index.php index.html;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass wordpress_php_fpm:9000;
  }
 }
}
