
services:

  nginx:
    build: ./requirements/nginx
    container_name: wp_nginx
    volumes:
      - wordpress_website_files:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "443:443"
    networks:
      - wp_network

  mariadb:
    build: ./requirements/mariadb
    container_name: wp_mariadb
    volumes:
      - wordpress_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ymizuniw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
    secrets:
      - db_root_password
      - db_password
    networks:
      - wp_network
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wp_wordpress
    volumes:
      - wordpress_website_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wp_network


secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  wordpress_website_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymizuniw/data/www'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymizuniw/data/db'

networks:
  wp_network:
    driver: bridge

